In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
apple = pd.read_csv('./data/apple_final.csv')

In [3]:
apple

           state          county        date  driving  walking  public
0        Alabama  Autauga County  2020-01-13   100.00      NaN     NaN
1        Alabama  Autauga County  2020-01-14    99.14      NaN     NaN
2        Alabama  Autauga County  2020-01-15   113.51      NaN     NaN
3        Alabama  Autauga County  2020-01-16   123.01      NaN     NaN
4        Alabama  Autauga County  2020-01-17   150.98      NaN     NaN
...          ...             ...         ...      ...      ...     ...
1175386  Wyoming    Uinta County  2021-07-28   360.69      NaN     NaN
1175387  Wyoming    Uinta County  2021-07-29   411.30      NaN     NaN
1175388  Wyoming    Uinta County  2021-07-30   468.75      NaN     NaN
1175389  Wyoming    Uinta County  2021-07-31   555.22      NaN     NaN
1175390  Wyoming    Uinta County  2021-08-01   524.77      NaN     NaN

[1175391 rows x 6 columns]

In [4]:
mask = apple['county'].apply(lambda s: True if (' County' in s or ' Parish' in s) else False)

In [6]:
apple_weird_names = apple['county'][mask == False]

In [11]:
apple_weird_names = apple_weird_names.unique().tolist()

In [12]:
google= pd.read_csv('./data/google_final.csv')

In [13]:
google.shape

(1339312, 9)

In [14]:
apple.shape

(1175391, 6)

In [16]:
mask2 = google['county'].apply(lambda s: True if (' County' in s or ' Parish' in s) else False)

In [18]:
google_weird_names = google['county'][mask2 == False]

In [19]:
google_weird_names.value_counts()

Fredericksburg             534
St. Louis                  534
Hampton                    534
Norfolk                    534
Fairbanks North Star       534
Baltimore                  534
Virginia Beach             534
Portsmouth                 534
Alexandria                 534
Chesapeake                 534
Roanoke                    534
Lynchburg                  534
Suffolk                    534
Manassas                   534
Anchorage                  534
Newport News               534
Richmond                   534
Harrisonburg               534
Matanuska-Susitna          534
Carson City                531
Danville                   530
Charlottesville            528
Petersburg                 528
Kenai Peninsula Borough    527
Fairfax                    523
Hopewell                   520
Colonial Heights           518
Winchester                 515
Waynesboro                 509
Martinsville               509
Bristol                    509
Salem                      509
Williamsburg               509
Manassas Park              509
Juneau                     509
Staunton                   509
Falls Church               509
Galax                      504
Emporia                    493
North Slope                478
Radford                    444
Franklin                   398
Ketchikan Gateway          377
Kodiak Island              376
Poquoson                   375
Covington                  372
Bethel                     365
Valdez-Cordova             361
Buena Vista                359
Sitka                      234
Norton                     115
Lexington                   88
Southeast Fairbanks         13
Nome                         1
Name: county, dtype: int64

In [20]:
def uniform_names(name):
    newname = name
    if 'Manassas Park' == name:
        for i in apple_weird_names:
            if name in i:
                newname = i
    elif 'Manassas' == name:
        for i in apple_weird_names:
            if name in i and i == 'Manassas City':
                newname = i
    else:
        for i in apple_weird_names:
            if name in i:
                newname = i
    return newname

In [21]:
google_cnames_adj = (google['county'].apply(lambda s: uniform_names(s)))

In [22]:
google_cnames_adj[mask2 == False].value_counts()

Alexandria City                 534
Roanoke City                    534
Portsmouth City                 534
Virginia Beach City             534
Lynchburg City                  534
St. Louis City                  534
Chesapeake City                 534
Baltimore City                  534
Harrisonburg City               534
Anchorage Municipality          534
Fairbanks North Star Borough    534
Matanuska-Susitna Borough       534
Hampton City                    534
Richmond City                   534
Newport News City               534
Manassas City                   534
Suffolk City                    534
Norfolk City                    534
Fredericksburg City             534
Carson City                     531
Danville City                   530
Charlottesville City            528
Petersburg City                 528
Kenai Peninsula Borough         527
Fairfax City                    523
Hopewell City                   520
Colonial Heights City           518
Winchester City                 515
Bristol City                    509
Salem City                      509
Juneau City and Borough         509
Manassas Park City              509
Williamsburg City               509
Waynesboro City                 509
Falls Church City               509
Martinsville City               509
Staunton City                   509
Galax                           504
Emporia                         493
North Slope                     478
Radford                         444
Franklin                        398
Ketchikan Gateway               377
Kodiak Island                   376
Poquoson                        375
Covington                       372
Bethel                          365
Valdez-Cordova                  361
Buena Vista                     359
Sitka                           234
Norton                          115
Lexington                        88
Southeast Fairbanks              13
Nome                              1
Name: county, dtype: int64

In [24]:
google['county'] = google_cnames_adj

In [26]:
google_states = pd.read_csv('./data/raw/google_states.csv')

In [27]:
google_dc = google_states[(google_states['state'] == 'District of Columbia')==True]

In [32]:
google_dc = google_dc.drop(columns = ['country', 'census_fips_code'])

In [34]:
google_dc.columns = ['state', 'county', 'date', 'ret_rec', 'gro_pharm', 'parks', 'transit', 'work', 'res']

In [36]:
google_dc['county'] = ['District of Columbia']*534

In [37]:
google_dc

,state,county,date,ret_rec,gro_pharm,parks,transit,work,res
4806,District of Columbia,District of Columbia,2020-02-15,-2,-2,13.0,-2.0,-2,-1
4807,District of Columbia,District of Columbia,2020-02-16,6,-1,37.0,3.0,0,-1
4808,District of Columbia,District of Columbia,2020-02-17,-10,-12,21.0,-39.0,-52,11
4809,District of Columbia,District of Columbia,2020-02-18,-5,-2,13.0,-3.0,-5,1
4810,District of Columbia,District of Columbia,2020-02-19,-2,-3,7.0,-3.0,-5,1
...,...,...,...,...,...,...,...,...,...
5335,District of Columbia,District of Columbia,2021-07-28,-34,-16,-4.0,-58.0,-52,13
5336,District of Columbia,District of Columbia,2021-07-29,-35,-17,-3.0,-58.0,-52,13
5337,District of Columbia,District of Columbia,2021-07-30,-27,-13,13.0,-52.0,-48,10
5338,District of Columbia,District of Columbia,2021-07-31,-29,-8,24.0,-38.0,-17,0
5339,District of Columbia,District of Columbia,2021-08-01,-31,-19,-1.0,-41.0,-19,3

In [38]:
google.shape

(1339312, 9)

In [39]:
google = google.append(google_dc, ignore_index = True)

In [40]:
google.shape

(1339846, 9)

In [43]:
google.to_csv('./data/google_final2.csv', index = False)

In [42]:
google[(google['state'] == 'District of Columbia')==True]

,state,county,date,ret_rec,gro_pharm,parks,transit,work,res
1339312,District of Columbia,District of Columbia,2020-02-15,-2.0,-2.0,13.0,-2.0,-2.0,-1.0
1339313,District of Columbia,District of Columbia,2020-02-16,6.0,-1.0,37.0,3.0,0.0,-1.0
1339314,District of Columbia,District of Columbia,2020-02-17,-10.0,-12.0,21.0,-39.0,-52.0,11.0
1339315,District of Columbia,District of Columbia,2020-02-18,-5.0,-2.0,13.0,-3.0,-5.0,1.0
1339316,District of Columbia,District of Columbia,2020-02-19,-2.0,-3.0,7.0,-3.0,-5.0,1.0
...,...,...,...,...,...,...,...,...,...
1339841,District of Columbia,District of Columbia,2021-07-28,-34.0,-16.0,-4.0,-58.0,-52.0,13.0
1339842,District of Columbia,District of Columbia,2021-07-29,-35.0,-17.0,-3.0,-58.0,-52.0,13.0
1339843,District of Columbia,District of Columbia,2021-07-30,-27.0,-13.0,13.0,-52.0,-48.0,10.0
1339844,District of Columbia,District of Columbia,2021-07-31,-29.0,-8.0,24.0,-38.0,-17.0,0.0
1339845,District of Columbia,District of Columbia,2021-08-01,-31.0,-19.0,-1.0,-41.0,-19.0,3.0

In [41]:
apple[(apple['state'] == 'District of Columbia')==True]

,state,county,date,driving,walking,public
125874,District of Columbia,District of Columbia,2020-01-13,100.00,100.00,100.00
125875,District of Columbia,District of Columbia,2020-01-14,105.82,99.07,100.78
125876,District of Columbia,District of Columbia,2020-01-15,109.02,109.61,103.92
125877,District of Columbia,District of Columbia,2020-01-16,110.37,104.16,105.02
125878,District of Columbia,District of Columbia,2020-01-17,123.98,123.16,112.26
...,...,...,...,...,...,...
126436,District of Columbia,District of Columbia,2021-07-28,139.68,133.11,91.83
126437,District of Columbia,District of Columbia,2021-07-29,143.83,137.60,92.78
126438,District of Columbia,District of Columbia,2021-07-30,168.36,184.67,105.62
126439,District of Columbia,District of Columbia,2021-07-31,162.86,205.75,105.37
126440,District of Columbia,District of Columbia,2021-08-01,121.62,131.53,80.36

In [45]:
mid = pd.read_csv('./data/zhvi_mid_clean.csv')

In [47]:
mid[(mid['state'] == 'District of Columbia')==True]

,county,state,Metro,StateCodeFIPS,MunicipalCodeFIPS,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,...,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30
104,District of Columbia,District of Columbia,Washington-Arlington-Alexandria,11,1,626364.0,625996.0,629531.0,632355.0,637087.0,...,654899.0,657608.0,661892.0,664967.0,666905.0,669264.0,673002.0,677222.0,684831.0,691888.0